examples/todolist - syncState/package.json
webpack, http-server and babel were missing
=> Update package.json to include missing packages

dist/bundle.js, src/rebase.js, tests/specs/re-base.spec.js
I ran into this in my own project.  Luckily, I was able to get a failing test by swapping two entries.  Let me know if anything else needs to be done!
=> Use snapshot.forEach when converting to array, fixes #38

README.md
API' name should be `removeBinding` at this moment.
=> Update Readme: clearBinding -> removeBinding

README.md
I only searched for ``` but there was a lot of code that was four space indented :)
=> More syntax highlighting

README.md, dist/bundle.js, src/rebase.js, tests/specs/re-base.spec.js
Adds the ability to register and remove a user.
I'll add a pr for changeEmail(), changePassword(), resetPassword() after this one gets merged.
Thanks!
=> Add `createUser` and `removeUser` methods

README.md
Great library, just a quick documentation fix for `removeUser`. :)
=> Fix `removeUser` docs in README

README.md, dist/bundle.js, src/rebase.js, tests/specs/re-base.spec.js
=> Get authentication data

README.md, package.json
Not sure your thoughts on this, but thought I'd throw it up anyway.
=> Add contributing info to readme

README.md
=> adds missing comma in readme example

README.md
I like clicking things on github :octocat:
=> add link to examples

README.md, dist/bundle.js, package.json, src/rebase.js, tests/specs/re-base.spec.js
Fix for #76 
Tried my hand at a matching test for it too. First pull request and first real unit test, please let me know what you think!
=> push() should return a Firebase reference for the generated location

README.md
in Post example, there is a template string but it is using single quotes
=> Changing quotes to backticks

README.md, dist/bundle.js, package.json, src/rebase.js, tests/specs/re-base.spec.js
For issue #99 This is a WIP. Keeps the existing re-base public api but is using the firebase 3.x library under the hood. Tests are flaky. I think they need to be refactored as there seems to be an inconsistency with the react component lifecycle methods and when the actual response comes back from Firebase. This is my current thought on why they are failing using this test as an example: 
```
it('listenTo\'s .then method gets invoked when the Firebase endpoint changes 
and correctly updates the component\'s state', function(done){
class TestComponent extends React.Component{
constructor(props){
super(props);
this.state = {
data: {}
}
}
componentWillMount(){
this.ref = base.listenTo(testEndpoint, {
context: this,
then(data){
this.setState({data}) 
}
});
}
componentDidMount(){ …
```
=> Firebase 3.x.x

README.md
It would be nicer to have ability to click on feature name and see API example
=> Make items in Features list links to API example

README.md, dist/bundle.js, package.json, src/rebase.js, tests/karma.conf.js, tests/specs/re-base.spec.js
Updates dependancies, fixes issue with tests running twice on save, rebuilds dist/bundle.js to include fix from #112 ... ooops
Fixes #84
=> Version 2.1.0

README.md, dist/bundle.js, package.json, src/rebase.js, tests/specs/re-base.spec.js
Pulls in update implementation from PR #92 and makes it compatible with firebase 3
=> Adds update method

README.md
Adds documentation that was needed as evidenced by #122 and #123
=> add doc updates to push and include error handling in examples

README.md, dist/bundle.js, src/rebase.js, tests/specs/re-base.spec.js
Resolves #123 
Returns the Firebase Promise from each of these methods. Non-breaking change. You can either use the .then callback or just use the Promise directly.
Also resolves #124 by adding an onFailure callback to fetch
=> Return Firebase Promise from .fetch, .update, and .post

README.md
PR resolves #137 
Previous docs were slightly incorrect and have now been updated based on the [firebase docs](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged). There is also a lot of other changes due to the `trim_trailing_whitespace = true` options specified in the .editorconfig file. Happy to remove these if need be, but IMO it made sense to leave the whitespace changes.
=> Update onAuth docs.

dist/bundle.js, src/lib/auth/authWithOAuthToken.js, src/rebase.js
Minor bugs. Love this library. Cheers!
=> add missing import statement;edit another

examples/github-notetaker/app/components/Profile.js, package.json, tests/specs/bindToState.spec.js, tests/specs/fetch.spec.js, tests/specs/post.spec.js, tests/specs/push.spec.js, tests/specs/syncState.spec.js
This PR changes the endpoints in the tests and the github notetaker example. I added some new security rules to the test database so we can start testing permissions errors and add handlers where they are needed.
=> update endpoints for new test db security rules

README.md, dist/bundle.js, package.json, src/lib/database/sync.js, src/lib/utils.js, tests/fixtures/dummyArrayOfObjects.js, tests/specs/syncState.spec.js
=> SyncState: Keep firebase generated keys when using asArray

dist/bundle.js, package.json, src/lib/database/sync.js, tests/specs/syncState.spec.js
Fixes #164 Calls onFailure with the component context.
=> Patch syncState onFailure

dist/bundle.js, package.json, src/lib/database/fetch.js, tests/specs/fetch.spec.js
=> fix firebase undefined error (#172)

README.md, dist/bundle.js, package.json, src/lib/database/fetch.js, src/lib/utils.js, tests/specs/auth.spec.js, tests/specs/bindToState.spec.js, tests/specs/createClass.spec.js, tests/specs/delete.spec.js, tests/specs/fetch.spec.js, tests/specs/listenTo.spec.js, tests/specs/post.spec.js, tests/specs/push.spec.js, tests/specs/remove.spec.js, tests/specs/removeBinding.spec.js, tests/specs/reset.spec.js, tests/specs/serverinfo.spec.js, tests/specs/services.spec.js, tests/specs/syncState.spec.js, tests/specs/update.spec.js, tests/specs/user.spec.js
=> Add IsNullable option

package.json, tests/fixtures/config.js
=> update test config to new db

README.md
@qwales1 let's try this again :)
=> Add caveat about functional setState in Re-base <3.

README.md, dist/bundle.js, package.json, src/lib/utils.js, tests/specs/bindToState.spec.js, tests/specs/listenTo.spec.js
=> Patch on failure

package-lock.json, package.json, tests/specs/bindToState.spec.js, tests/specs/createClass.spec.js, tests/specs/fetch.spec.js, tests/specs/listenTo.spec.js, tests/specs/post.spec.js, tests/specs/push.spec.js, tests/specs/remove.spec.js, tests/specs/removeBinding.spec.js, tests/specs/reset.spec.js, tests/specs/serverinfo.spec.js, tests/specs/syncState.spec.js, tests/specs/update.spec.js
Run tests in React 16 and account for change to firebase/database API. It doesn't export a function anymore like past versions
=> Update tests react 16

README.md
I'm so sorry but I really had to open this pull request :100: :+1:
=> Nitpicky typo - Sorry :3

README.md
I found this issue when try to initialize my firebase :
> - install firebase 14.3.0 or higher
> - try to access firestore (write, read, subscribe, etc)
Basically i just insert `{timestampsInSnapshots: true}` into firebase instance.
Only `README.md` file.
=> Update readme regarding firestore timestamps issue
